In [1]:
import numpy as np
import pandas as pd

In [2]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is 6220-5780

 Directory of D:\goat mytra

15-06-2024  22:49    <DIR>          .
15-06-2024  22:49    <DIR>          ..
15-06-2024  20:29                 9 .gitignore
15-06-2024  20:15    <DIR>          .ipynb_checkpoints
15-06-2024  22:47    <DIR>          __pycache__
15-06-2024  17:04                 0 data_ingestion.py
15-06-2024  19:09                 0 Dockerfile
15-06-2024  20:21               673 exceptions.py
15-06-2024  22:47            50,420 Experiment Notebook (meat quality) .ipynb
15-06-2024  22:49            48,623 Experiment Notebook (milk quality) .ipynb
15-06-2024  22:47             4,271 fast_api.py
15-06-2024  17:04                 0 feature_engineering.py
15-06-2024  22:41             5,369 goat_dataset.csv
15-06-2024  20:42               269 goat_inputs.py
15-06-2024  20:20               459 logger.py
15-06-2024  20:21    <DIR>          logs
15-06-2024  19:11                 0 main_pipeline.py
15-06-2024  22:46               720 meat_quality_model.pkl
15-06-2024  22:47            12,097 milk_quality_model.pkl
15-06-2024  19:06                 0 MLflow.py
15-06-2024  17:05                 0 model_trainer.py
15-06-2024  19:13    <DIR>          myvenv
15-06-2024  21:07             4,790 preprocessor.pkl
15-06-2024  22:12             3,975 preprocessor_.pkl
15-06-2024  20:35               191 requirements.txt
15-06-2024  19:08    <DIR>          rust_functions
              19 File(s)        131,866 bytes
               7 Dir(s)  972,911,169,536 bytes free

In [3]:
df = pd.read_csv("goat_dataset.csv")

## Exploratory Data Analysis

In [4]:
df.head()

,owner_name,adhaar_number,goat_id,milk_in_litres,age,height,weight,pregnancy,behavior,gender,hay_grass_intake,meat_quality_of_the_goat,milk_quality_of_the_goat
0,Aarav,123456789012,1,10,2,70,35,no,docile,female,5,4,5
1,Vihaan,987654321098,2,15,3,75,40,yes,normal,female,6,3,4
2,Vivaan,456123789012,3,20,4,80,45,no,aggressive,male,7,5,3
3,Aadhya,321654987012,4,8,1,65,30,no,docile,male,4,2,2
4,Anaya,654789123456,5,12,5,85,50,yes,normal,female,8,4,5

In [5]:
df.shape

(90, 13)

In [6]:
df.describe()

,adhaar_number,goat_id,milk_in_litres,age,height,weight,hay_grass_intake,meat_quality_of_the_goat,milk_quality_of_the_goat
count,9.000000e+01,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,5.166191e+11,45.500000,16.055556,3.577778,78.500000,41.944444,6.655556,3.722222,3.488889
std,2.969927e+11,26.124701,4.645551,1.437677,7.295142,7.199190,1.515175,1.081279,1.083528
min,1.234568e+11,1.000000,8.000000,1.000000,65.000000,30.000000,4.000000,2.000000,2.000000
25%,2.583691e+11,23.250000,12.000000,2.000000,72.000000,36.000000,5.000000,3.000000,3.000000
50%,4.561238e+11,45.500000,16.000000,4.000000,80.000000,42.000000,7.000000,4.000000,3.000000
75%,7.894561e+11,67.750000,19.750000,5.000000,85.000000,48.000000,8.000000,5.000000,4.000000
max,9.876543e+11,90.000000,25.000000,6.000000,90.000000,55.000000,9.000000,5.000000,5.000000

## Feature Engineering

In [7]:
df.drop(["owner_name" , "adhaar_number" , "goat_id"] , axis = 1 , inplace = True)

In [8]:
df.shape

(90, 10)

In [9]:
pregnancy_dict = {
    "no" : 0,
    "yes" : 1
}
df['pregnancy'] = df['pregnancy'].map(pregnancy_dict)

In [10]:
behavior_dict = {
    "docile" : 0,
    "normal" : 1,
    "aggressive" : 2
}
df['behavior'] = df['behavior'].map(behavior_dict)

In [11]:
gender_dict = {
    "female" : 0,
    "male" : 1
}
df['gender'] = df['gender'].map(gender_dict)

In [12]:
# import pandas as pd
# from sklearn.preprocessing import OneHotEncoder, StandardScaler
# from sklearn.compose import ColumnTransformer
# from sklearn.impute import SimpleImputer
# from sklearn.pipeline import Pipeline

In [13]:
df.columns

Index(['milk_in_litres', 'age', 'height', 'weight', 'pregnancy', 'behavior',
       'gender', 'hay_grass_intake', 'meat_quality_of_the_goat',
       'milk_quality_of_the_goat'],
      dtype='object')

In [14]:
# numerical_columns = ["milk_in_litres" , "age" , "height" , "weight" , "hay_grass_intake"]
# categorical_columns = ["pregnancy" , "behavior" , "gender"]

In [15]:
## StandardScaler for numerical columns
## OneHotEncoding for categorical columns

In [16]:
# numerical_pipeline = Pipeline(
#     steps = [
#         ("imputer" , SimpleImputer(strategy = "median")),
#         ("scaler" , StandardScaler())
#     ]
# )

# categorical_pipeline = Pipeline(
#     steps=[
#         ("imputer" , SimpleImputer(strategy = "most_frequent")),
#         ("one_hot_encoder" , OneHotEncoder()),
#         ("scaler" , StandardScaler(with_mean = False))
#     ]
# )

# preprocessor = ColumnTransformer(
#                 [
#                     ("numerical_pipeline",numerical_pipeline,numerical_columns),
#                     ("categorical_pipeline",categorical_pipeline,categorical_columns)
#                 ]
# )

## milk_quality_of_the_cow

In [17]:
x = df.drop(["meat_quality_of_the_goat" , "milk_quality_of_the_goat"] , axis = 1 )
y = df[["milk_quality_of_the_goat"]]

In [18]:
from sklearn.model_selection import train_test_split

# Assuming X and y are your features and labels respectively
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"Training set size: {x_train.shape[0]}")
print(f"Test set size: {x_test.shape[0]}")

Training set size: 72
Test set size: 18

In [19]:
# x_train = preprocessor.fit_transform(x_train)
# x_test = preprocessor.transform(x_test)

In [20]:
x_train.shape

(72, 8)

In [21]:
x_test.shape

(18, 8)

## Model Building

### Giving every model a chance along with grid search cv implementation

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [23]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\maste\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\maste\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\maste\anaconda3\lib\site-packages (from xgboost) (1.11.4)

In [24]:
X_train = x_train
X_test = x_test

In [25]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print(y_train_pred)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

[[3.21983802]
 [3.40174097]
 [3.11937993]
 [3.96148418]
 [3.10797539]
 [3.48247881]
 [3.11937993]
 [3.51812448]
 [3.21983802]
 [2.96299958]
 [3.56587532]
 [3.14845035]
 [3.36278295]
 [3.3453631 ]
 [3.5340226 ]
 [3.36278295]
 [3.65133922]
 [3.26100333]
 [3.40174097]
 [3.51812448]
 [2.65301967]
 [3.5340226 ]
 [2.96299958]
 [2.98710144]
 [3.60255468]
 [3.73473573]
 [3.1924056 ]
 [2.65008048]
 [3.65133922]
 [3.1924056 ]
 [2.96299958]
 [3.5340226 ]
 [3.66891947]
 [3.65133922]
 [3.52596678]
 [3.65133922]
 [3.10797539]
 [2.65301967]
 [3.21983802]
 [4.99988653]
 [3.20381014]
 [2.98710144]
 [3.87775384]
 [3.51812448]
 [3.73473573]
 [2.42263217]
 [3.79332363]
 [3.66891947]
 [3.66891947]
 [3.73473573]
 [3.52596678]
 [2.65301967]
 [3.79332363]
 [3.40174097]
 [3.36278295]
 [3.87775384]
 [4.99988653]
 [4.99988653]
 [3.96148418]
 [4.81948341]
 [2.84731144]
 [3.60255468]
 [2.84731144]
 [3.87775384]
 [3.20381014]
 [3.51812448]
 [3.36278295]
 [3.20381014]
 [3.11937993]
 [3.56587532]
 [4.62572196]
 [4.81948341]]
Linear Regression
Model performance for Training set
- Root Mean Squared Error: 0.9058
- Mean Absolute Error: 0.7759
- R2 Score: 0.2614
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.9201
- Mean Absolute Error: 0.7502
- R2 Score: 0.3780
===================================


[3.48843013 3.49044992 3.48371729 3.4816975  3.47833119 3.49516275
 3.48371729 3.4870836  3.48843013 3.48641034 3.48506381 3.49044992
 3.48035097 3.49044992 3.49516275 3.48035097 3.49516275 3.49044992
 3.49044992 3.4870836  3.48371729 3.49516275 3.48641034 3.4816975
 3.4870836  3.48506381 3.47833119 3.48035097 3.49516275 3.47833119
 3.48641034 3.49516275 3.48641034 3.49516275 3.48237076 3.49516275
 3.47833119 3.48371729 3.48843013 3.49179644 3.48371729 3.4816975
 3.48035097 3.4870836  3.48506381 3.48506381 3.48035097 3.48641034
 3.48641034 3.48506381 3.48237076 3.48371729 3.48035097 3.49044992
 3.48035097 3.48035097 3.49179644 3.49179644 3.4816975  3.48506381
 3.48843013 3.4870836  3.48843013 3.48035097 3.48371729 3.4870836
 3.48035097 3.48371729 3.48371729 3.48506381 3.49516275 3.48506381]
Lasso
Model performance for Training set
- Root Mean Squared Error: 1.0534
- Mean Absolute Error: 0.9293
- R2 Score: 0.0012
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 1.1679
- Mean Absolute Error: 1.0532
- R2 Score: -0.0021
===================================


[[3.26178917]
 [3.39305239]
 [3.13625355]
 [3.91964954]
 [3.13375657]
 [3.55770346]
 [3.13625355]
 [3.54509691]
 [3.26178917]
 [2.99894067]
 [3.58234926]
 [3.15670389]
 [3.34840694]
 [3.29036833]
 [3.50286436]
 [3.34840694]
 [3.71526913]
 [3.3006995 ]
 [3.39305239]
 [3.54509691]
 [2.67469426]
 [3.50286436]
 [2.99894067]
 [3.06378939]
 [3.62387974]
 [3.73991493]
 [3.2125394 ]
 [2.74897878]
 [3.71526913]
 [3.2125394 ]
 [2.99894067]
 [3.50286436]
 [3.58035969]
 [3.71526913]
 [3.50438629]
 [3.71526913]
 [3.13375657]
 [2.67469426]
 [3.26178917]
 [4.87744497]
 [3.21503639]
 [3.06378939]
 [3.84118743]
 [3.54509691]
 [3.73991493]
 [2.56892344]
 [3.7624046 ]
 [3.58035969]
 [3.58035969]
 [3.73991493]
 [3.50438629]
 [2.67469426]
 [3.7624046 ]
 [3.39305239]
 [3.34840694]
 [3.84118743]
 [4.87744497]
 [4.87744497]
 [3.91964954]
 [4.62346517]
 [2.92667405]
 [3.62387974]
 [2.92667405]
 [3.84118743]
 [3.21503639]
 [3.54509691]
 [3.34840694]
 [3.21503639]
 [3.13625355]
 [3.58234926]
 [4.57112928]
 [4.62346517]]
Ridge
Model performance for Training set
- Root Mean Squared Error: 0.9079
- Mean Absolute Error: 0.7774
- R2 Score: 0.2581
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.9430
- Mean Absolute Error: 0.7839
- R2 Score: 0.3466
===================================


[[2.4]
 [2.4]
 [4.4]
 [4.2]
 [2.2]
 [3.8]
 [4.4]
 [3.6]
 [2.4]
 [3.2]
 [3.6]
 [2.4]
 [3.4]
 [2.4]
 [3.8]
 [3.4]
 [3.6]
 [2.6]
 [2.4]
 [3.6]
 [3. ]
 [3.8]
 [3.2]
 [4. ]
 [3.4]
 [3.4]
 [2.2]
 [3.6]
 [3.6]
 [2.2]
 [3.2]
 [3.8]
 [3.8]
 [3.6]
 [3.6]
 [3.6]
 [2.2]
 [3. ]
 [2.4]
 [3.8]
 [4.4]
 [4. ]
 [4.2]
 [3.6]
 [3.4]
 [3.6]
 [3.6]
 [3.8]
 [3.8]
 [3.4]
 [3.6]
 [3. ]
 [3.6]
 [2.4]
 [3.4]
 [4.2]
 [3.8]
 [3.8]
 [4.2]
 [4.4]
 [3.4]
 [3.4]
 [3.4]
 [4.2]
 [4.4]
 [3.6]
 [3.4]
 [4.4]
 [4.4]
 [3.6]
 [3.8]
 [4.4]]
K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 0.7047
- Mean Absolute Error: 0.6111
- R2 Score: 0.5529
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.7958
- Mean Absolute Error: 0.7000
- R2 Score: 0.5347
===================================


[2.         2.         4.66666667 5.         2.         2.
 4.66666667 3.75       2.         3.33333333 4.         3.
 3.         3.         4.         3.         4.         3.
 2.         3.75       2.         4.         3.33333333 4.
 3.         3.         2.         2.         4.         2.
 3.33333333 4.         5.         4.         3.         4.
 2.         2.         2.         5.         4.         4.
 5.         3.75       3.         4.         3.         5.
 5.         3.         3.         2.         3.         2.
 3.         5.         5.         5.         5.         4.
 3.         3.         3.         5.         4.         3.75
 3.         4.         4.66666667 4.         5.         4.        ]
Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.2907
- Mean Absolute Error: 0.1042
- R2 Score: 0.9239
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0786
- Mean Absolute Error: 0.0185
- R2 Score: 0.9955
===================================


[2.05       2.06       4.66716667 4.71       2.04       2.66
 4.66716667 3.74695635 2.05       3.48233333 3.92       2.78
 2.99       2.96       3.84       2.99       3.96       3.36
 2.06       3.74695635 2.06       3.84       3.48233333 3.94933333
 3.06266667 3.0475     2.02       2.488      3.96       2.02
 3.48233333 3.84       4.91       3.96       3.055      3.96
 2.04       2.06       2.05       4.94       4.046      3.94933333
 4.9        3.74695635 3.0475     3.86       3.31       4.91
 4.91       3.0475     3.055      2.06       3.31       2.06
 2.99       4.9        4.94       4.94       4.71       3.982
 3.09547619 3.06266667 3.09547619 4.9        4.046      3.74695635
 2.99       4.046      4.66716667 3.92       4.12       3.982     ]
Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 0.3416
- Mean Absolute Error: 0.1987
- R2 Score: 0.8949
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.2368
- Mean Absolute Error: 0.1623
- R2 Score: 0.9588
===================================

C:\Users\maste\AppData\Local\Temp\ipykernel_11144\415202671.py:26: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train) # Train model

[2.0000017 1.9999473 4.6663003 4.99904   2.0003154 2.003757  4.6663003
 3.7495708 2.0000017 3.333157  3.9995754 2.9971035 2.9999423 3.0021122
 3.9996748 2.9999423 3.999951  3.0014243 1.9999473 3.7495708 2.0001683
 3.9996748 3.333157  4.000126  3.0012546 3.0006027 2.0003154 2.0026336
 3.999951  2.0003154 3.333157  3.9996748 5.00006   3.999951  3.000268
 3.999951  2.0003154 2.0001683 2.0000017 4.999756  4.000235  4.000126
 4.999544  3.7495708 3.0006027 3.9971175 3.0004296 5.00006   5.00006
 3.0006027 3.000268  2.0001683 3.0004296 1.9999473 2.9999423 4.999544
 4.999756  4.999756  4.99904   4.0001016 3.0000057 3.0012546 3.0000057
 4.999544  4.000235  3.7495708 2.9999423 4.000235  4.6663003 3.9995754
 4.996776  4.0001016]
XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 0.2907
- Mean Absolute Error: 0.1047
- R2 Score: 0.9239
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0967
- Mean Absolute Error: 0.0330
- R2 Score: 0.9931
===================================


[2.71428571 2.5625     4.25       4.5        2.125      2.71428571
 4.25       3.33333333 2.71428571 2.96666667 3.53846154 2.79545455
 3.         3.         3.2        3.         4.         3.
 2.5625     3.33333333 2.79545455 3.2        2.96666667 4.16666667
 3.33333333 3.625      2.125      2.96666667 4.         2.125
 2.96666667 3.2        4.33333333 4.         3.26315789 4.
 2.125      2.79545455 2.71428571 4.66666667 4.25       4.16666667
 4.33333333 3.33333333 3.625      3.4        3.875      4.33333333
 4.33333333 3.625      3.26315789 2.79545455 3.875      2.5625
 3.         4.33333333 4.66666667 4.66666667 4.5        3.77777778
 3.         3.33333333 3.         4.33333333 4.25       3.33333333
 3.         4.25       4.25       3.53846154 4.77777778 3.77777778]
AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 0.5687
- Mean Absolute Error: 0.4705
- R2 Score: 0.7088
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.5404
- Mean Absolute Error: 0.4850
- R2 Score: 0.7854
===================================

C:\Users\maste\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [26]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

                Model Name  R2_Score
4            Decision Tree  0.995465
6             XGBRegressor  0.993127
5  Random Forest Regressor  0.958820
7       AdaBoost Regressor  0.785425
3    K-Neighbors Regressor  0.534694
0        Linear Regression  0.377955
2                    Ridge  0.346627
1                    Lasso -0.002136

## KNN Performs the Best

In [27]:
    model = KNeighborsRegressor(n_neighbors=5)
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print(y_train_pred)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

[[2.4]
 [2.4]
 [4.4]
 [4.2]
 [2.2]
 [3.8]
 [4.4]
 [3.6]
 [2.4]
 [3.2]
 [3.6]
 [2.4]
 [3.4]
 [2.4]
 [3.8]
 [3.4]
 [3.6]
 [2.6]
 [2.4]
 [3.6]
 [3. ]
 [3.8]
 [3.2]
 [4. ]
 [3.4]
 [3.4]
 [2.2]
 [3.6]
 [3.6]
 [2.2]
 [3.2]
 [3.8]
 [3.8]
 [3.6]
 [3.6]
 [3.6]
 [2.2]
 [3. ]
 [2.4]
 [3.8]
 [4.4]
 [4. ]
 [4.2]
 [3.6]
 [3.4]
 [3.6]
 [3.6]
 [3.8]
 [3.8]
 [3.4]
 [3.6]
 [3. ]
 [3.6]
 [2.4]
 [3.4]
 [4.2]
 [3.8]
 [3.8]
 [4.2]
 [4.4]
 [3.4]
 [3.4]
 [3.4]
 [4.2]
 [4.4]
 [3.6]
 [3.4]
 [4.4]
 [4.4]
 [3.6]
 [3.8]
 [4.4]]
AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 0.7047
- Mean Absolute Error: 0.6111
- R2 Score: 0.5529

In [28]:
    # model = LinearRegression()
    # model.fit(X_train, y_train) # Train model

    # # Make predictions
    # y_train_pred = model.predict(X_train)
    # y_test_pred = model.predict(X_test)

    # print(y_train_pred)
    
    # # Evaluate Train and Test dataset
    # model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    # model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    # print(list(models.keys())[i])
    # model_list.append(list(models.keys())[i])
    
    # print('Model performance for Training set')
    # print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    # print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    # print("- R2 Score: {:.4f}".format(model_train_r2))

In [31]:
import pickle

In [32]:
with open('milk_quality_model.pkl', 'wb') as file:
    pickle.dump(model, file)